Question 1:What is the probability of a person playing when the weather is sunny? Find P(Yes|Sunny).


In [1]:
print("P(Yes|Sunny) = 3/5")

P(Yes|Sunny) = 3/5


Question 2:Import iris dataset from sklearn.

In [54]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
%matplotlib inline

In [42]:
df = load_iris()
x=df.data
y=df.target
x.shape, y.shape

((150, 4), (150,))

In [43]:
#perform split on training data
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size = 0.3, random_state = 2)

In [44]:
#gaussian NB
gauss_model = GaussianNB()

In [46]:
#gaussian fit
gauss_model.fit(x_train, y_train)

GaussianNB(priors=None)

In [51]:
#prediction matrix
gauss_pred = gauss_model.predict(x_test)

In [52]:
#classification matrics
print(classification_report(y_test, gauss_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        17
          1       1.00      0.93      0.97        15
          2       0.93      1.00      0.96        13

avg / total       0.98      0.98      0.98        45



In [53]:
#confusion metrics
print(confusion_matrix(y_test, gauss_pred))

[[17  0  0]
 [ 0 14  1]
 [ 0  0 13]]


In [55]:
#accuracy score
accuracy_score(y_test,gauss_pred)

0.9777777777777777

In [56]:
#perform Multinomial NB
from sklearn.naive_bayes import MultinomialNB
multi_model = MultinomialNB()
multi_model.fit(x_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [57]:
multi_pred = multi_model.predict(x_test)
multi_pred

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 2, 1,
       2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 2, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1,
       0])

In [58]:
#classification matrics
print(classification_report(y_test, multi_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        17
          1       1.00      0.73      0.85        15
          2       0.76      1.00      0.87        13

avg / total       0.93      0.91      0.91        45



In [59]:
#accuracy for multinomial NB
accuracy_score(y_test,multi_pred)

0.9111111111111111

In [60]:
#confusion matrix for Multinomial NB
print(confusion_matrix(y_test, multi_pred))

[[17  0  0]
 [ 0 11  4]
 [ 0  0 13]]
