In [1]:
#importing packages
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.metrics import *

Question 1: Import dataset from sklearn.

In [2]:
df = load_digits()
x = df.data
y = df.target
x.shape, y.shape

((1797, 64), (1797,))

Question 2: Perform feature scaling.

In [3]:
x = StandardScaler().fit_transform(x)

Question 3: Perform PCA. Take any value for components.

In [4]:
#Principal Component Analysis
A = PCA(n_components =15)

In [5]:
new_x=A.fit_transform(x)
new_x

array([[ 1.9141802 , -0.95440215, -3.94593794, ...,  0.2584649 ,
        -0.21622708,  0.78042605],
       [ 0.5890335 ,  0.92453726,  3.92485273, ..., -0.07933692,
        -0.35337398, -0.68637197],
       [ 1.3020475 , -0.31723809,  3.02322716, ..., -0.59204397,
        -0.96917649, -1.18191612],
       ...,
       [ 1.02258865, -0.14784463,  2.46993056, ..., -0.36889488,
         0.24536058,  0.31271319],
       [ 1.07603102, -0.3808221 , -2.45529607, ...,  0.18733486,
        -0.75567877, -0.04112682],
       [-1.25773153, -2.22747388,  0.28355871, ...,  0.16747805,
         0.69802332,  1.78461848]])

Question 4: Split data into training and testing sets.

In [6]:
#perform split on training data
x_train,x_test,y_train,y_test  = train_test_split(new_x,y,test_size = 0.2, random_state =20)

Question 5: Perform classification (logistic regression).

In [7]:
#Logistic refression
regressor = LogisticRegression()
regressor.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [8]:
pred = regressor.predict(x_test)

Question 6: Print the following: 
a. Accuracy score
b. Confusion Matrix
c. Classification Report

In [9]:
#accuracy score
accuracy_score(y_test,pred)*100

94.16666666666667

In [10]:
#confusion matrix
print(confusion_matrix(y_test, pred))

[[37  0  0  0  0  0  0  0  0  0]
 [ 0 30  0  0  0  0  0  0  1  0]
 [ 0  0 27  0  1  0  0  0  0  0]
 [ 0  0  1 35  0  0  0  2  0  0]
 [ 0  0  0  0 39  0  0  0  0  2]
 [ 1  0  0  0  0 32  0  0  0  0]
 [ 0  3  0  0  0  0 42  0  0  0]
 [ 0  0  0  0  0  0  0 40  0  0]
 [ 0  2  0  1  0  0  1  1 29  1]
 [ 0  1  0  0  0  1  0  1  1 28]]


In [11]:
#classification report
print(classification_report(y_test, pred))

             precision    recall  f1-score   support

          0       0.97      1.00      0.99        37
          1       0.83      0.97      0.90        31
          2       0.96      0.96      0.96        28
          3       0.97      0.92      0.95        38
          4       0.97      0.95      0.96        41
          5       0.97      0.97      0.97        33
          6       0.98      0.93      0.95        45
          7       0.91      1.00      0.95        40
          8       0.94      0.83      0.88        35
          9       0.90      0.88      0.89        32

avg / total       0.94      0.94      0.94       360

