Question 1:Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements using basic numpy functions.

In [2]:
import numpy as nm

In [4]:
#numpy array
numpy_array = nm.random.rand(10,1)
numpy_array

array([[0.8305515 ],
       [0.94747928],
       [0.68037805],
       [0.56086847],
       [0.30741861],
       [0.92246887],
       [0.6496719 ],
       [0.71621558],
       [0.45217144],
       [0.67911136]])

In [5]:
#mean of the array
nm.mean(numpy_array)

0.6746335046028391

Question 2: Create a numpy array with 20 elements of the shape(20,1) using np.random find the variance and standard deviation of the elements.

In [7]:
#numpy array
na= nm.random.rand(20,1)
na

array([[0.50745949],
       [0.66844437],
       [0.17688531],
       [0.72114277],
       [0.93201388],
       [0.36800786],
       [0.8388458 ],
       [0.04978318],
       [0.24625381],
       [0.42591551],
       [0.68476503],
       [0.67508995],
       [0.23775016],
       [0.24532578],
       [0.04358528],
       [0.02974497],
       [0.76048052],
       [0.47084581],
       [0.87629675],
       [0.15635369]])

In [8]:
#variance
nm.var(na)

0.08451471483455116

In [9]:
#standard deviation
nm.std(na)

0.29071414625805736

Question 3:Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25). Using basic numpy math functions only find the sum of all the elements of the new matrix.

In [10]:
array_a=nm.random.rand(10,20)
array_b=nm.random.rand(20,25)
print(array_a)
print(array_b)

[[0.77720282 0.39956584 0.81070031 0.01011572 0.66002611 0.86015924
  0.93367413 0.7058796  0.57570173 0.33313936 0.05089203 0.62607845
  0.55638667 0.11092929 0.74247562 0.00642068 0.66249006 0.49725746
  0.36686727 0.45736732]
 [0.16088927 0.77325141 0.17312743 0.17579916 0.00457612 0.89300243
  0.18949997 0.23243149 0.494563   0.8941886  0.50780369 0.72961017
  0.45568602 0.40445039 0.90367968 0.20994221 0.17415025 0.25014921
  0.08254332 0.13796874]
 [0.77220629 0.70415633 0.67132109 0.93167856 0.81731731 0.56128937
  0.21303128 0.31697251 0.73947931 0.35908355 0.99376824 0.68498978
  0.73781754 0.45206297 0.93118437 0.30799173 0.56690987 0.14269436
  0.74104369 0.5060236 ]
 [0.35305541 0.40824396 0.80886972 0.06889646 0.0666453  0.9476229
  0.61595285 0.88765783 0.87044708 0.5939539  0.00206597 0.36770077
  0.39680747 0.67986808 0.72704028 0.56768919 0.57690792 0.91647963
  0.41117805 0.51836437]
 [0.82298389 0.3158367  0.33752774 0.79594668 0.88143266 0.65634857
  0.77394269 0.94

In [12]:
#matrix multiplication
multi=nm.matmul(array_a,array_b)
print(multi)

[[4.05492702 5.27041815 5.34759092 4.90558622 6.22949241 4.84574396
  4.49846016 4.79771793 5.69916561 4.69799365 4.02656561 4.67269202
  4.76060469 4.58106587 4.0571308  5.82498006 4.31815522 5.32900727
  5.78567463 4.68183631 5.57810604 6.18371734 5.4783673  4.74649231
  5.60265049]
 [3.22870485 4.55031994 4.25008133 3.85608485 4.35853326 3.50841316
  3.09411394 3.40803843 3.97212716 3.42829644 3.56164066 2.43616976
  3.23328884 4.26399191 3.08790597 3.80265274 3.1807806  4.15377865
  4.63256963 2.8291403  4.22520692 4.60858165 4.95168313 3.95458791
  4.5809718 ]
 [4.79461121 6.91627875 6.90783189 6.02836762 6.86396672 5.32186695
  5.07130118 5.07215323 6.35122556 5.28340658 5.90104531 5.10774694
  5.21778404 6.48032222 5.53341741 6.87758045 5.23324328 7.10302606
  6.15111125 5.64716417 6.73999342 7.32626494 6.49335409 5.89511781
  6.79800915]
 [4.23335617 6.21899397 6.38945058 4.39282556 6.30513651 5.30819798
  4.88783656 4.86903784 5.48558682 5.13173622 4.49876485 4.52490864
  5.19

In [13]:
#sum of all elements of new matrix
matsum = nm.sum(multi)
print(matsum)

1260.4365421379714


In [16]:
#shape of the product matrix
multi.shape

(10, 25)

Question 4:Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that each element is the following function applied on each element of A. 

f(x)=1 / (1 + exp(-x)).

In [4]:
numpy_arr = nm.random.rand(10,1)
numpy_arr

array([[0.52631867],
       [0.47943475],
       [0.43910819],
       [0.22900106],
       [0.90006572],
       [0.43552988],
       [0.48157724],
       [0.41230405],
       [0.59256438],
       [0.09252362]])

In [5]:
def fun(x,axis):
    return 1/(1+ nm.exp(-x))

In [9]:
nm.apply_over_axes(fun,numpy_arr,1)

array([[0.62862409],
       [0.61761439],
       [0.60804651],
       [0.55700138],
       [0.71096301],
       [0.60719338],
       [0.61812025],
       [0.60164022],
       [0.64395332],
       [0.52311442]])