In [1]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_digits
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import *
%matplotlib inline

C:\Users\karan\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Question 1:Load the dataset from sklearn

In [2]:
#load_digits datasets
df = load_digits()
x=df.data
y=df.target
x.shape, y.shape

((1797, 64), (1797,))

Question 2:Split the dataset into training and testing sets 

In [3]:
#perform split on training data
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size = 0.3, random_state = 5)

Question 3:Use SVM with kernels
    For every kernel, print the following:
a. Confusion Matrix
b. Classification Report

In [6]:
#SVC having kernel
svm_model1 = SVC(C=0.5,kernel='linear',degree=3,gamma=3)

In [7]:
svm_model1.fit(x_train,y_train)

SVC(C=0.5, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=3, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [8]:
#prediction for linear kernel
pred1=svm_model1.predict(x_test)

In [10]:
#accuracy score
accuracy_score(y_test,pred1)

0.9833333333333333

In [11]:
#confusion matrix for linear kernel
confusion_matrix(y_test,pred1)

array([[58,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 52,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 58,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1, 56,  0,  1,  0,  0,  0,  1],
       [ 0,  1,  0,  0, 42,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 63,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0, 47,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 58,  0,  1],
       [ 0,  1,  0,  0,  0,  0,  0,  0, 48,  1],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  0, 49]], dtype=int64)

In [12]:
#classification report
print(classification_report(y_test,pred1))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        58
          1       0.96      1.00      0.98        52
          2       0.98      1.00      0.99        58
          3       1.00      0.95      0.97        59
          4       1.00      0.98      0.99        43
          5       0.97      0.98      0.98        64
          6       1.00      1.00      1.00        47
          7       1.00      0.98      0.99        59
          8       1.00      0.96      0.98        50
          9       0.92      0.98      0.95        50

avg / total       0.98      0.98      0.98       540



In [13]:
#SVC having polynomial kernel
svm_model2 = SVC(C=0.5,kernel='poly',degree = 8, gamma = 4)

In [14]:
svm_model2.fit(x_train,y_train)

SVC(C=0.5, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma=4, kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [16]:
#prediction for polynomial kernel
pred2=svm_model2.predict(x_test)

In [17]:
#accuracy score of polynomial kernel
accuracy_score(y_test,pred2)

0.975925925925926

In [18]:
#confusion matrix
confusion_matrix(y_test,pred2)

array([[57,  0,  0,  0,  0,  0,  1,  0,  0,  0],
       [ 0, 49,  0,  0,  1,  1,  0,  0,  1,  0],
       [ 0,  0, 57,  0,  0,  0,  0,  1,  0,  0],
       [ 0,  0,  0, 57,  0,  1,  0,  0,  1,  0],
       [ 0,  0,  0,  0, 42,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0, 63,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0, 46,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 58,  0,  1],
       [ 0,  1,  0,  0,  0,  0,  0,  0, 49,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  0, 49]], dtype=int64)

In [19]:
#classification report
print(classification_report(y_test,pred2))

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        58
          1       0.98      0.94      0.96        52
          2       1.00      0.98      0.99        58
          3       1.00      0.97      0.98        59
          4       0.98      0.98      0.98        43
          5       0.95      0.98      0.97        64
          6       0.98      0.98      0.98        47
          7       0.97      0.98      0.97        59
          8       0.94      0.98      0.96        50
          9       0.96      0.98      0.97        50

avg / total       0.98      0.98      0.98       540



In [20]:
#SVC having rbf kernel
svm_model3 = SVC(kernel='rbf')

In [21]:
svm_model3.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [22]:
#prediction for rbf kernel
pred3=svm_model3.predict(x_test)

In [23]:
#accuracy score
accuracy_score(y_test,pred3)

0.32407407407407407

In [24]:
#confusion matrix
confusion_matrix(y_test,pred3)

array([[23,  0,  0,  0, 35,  0,  0,  0,  0,  0],
       [ 0, 18,  0,  0, 34,  0,  0,  0,  0,  0],
       [ 0,  0, 11,  0, 47,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 10, 49,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 43,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 62,  2,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 19,  0, 28,  0,  0,  0],
       [ 0,  0,  0,  0, 45,  0,  0, 14,  0,  0],
       [ 0,  0,  0,  0, 45,  0,  0,  0,  5,  0],
       [ 0,  0,  0,  0, 29,  0,  0,  0,  0, 21]], dtype=int64)

In [25]:
#classification report
print(classification_report(y_test,pred3))

             precision    recall  f1-score   support

          0       1.00      0.40      0.57        58
          1       1.00      0.35      0.51        52
          2       1.00      0.19      0.32        58
          3       1.00      0.17      0.29        59
          4       0.11      1.00      0.19        43
          5       1.00      0.03      0.06        64
          6       1.00      0.60      0.75        47
          7       1.00      0.24      0.38        59
          8       1.00      0.10      0.18        50
          9       1.00      0.42      0.59        50

avg / total       0.93      0.32      0.38       540



In [26]:
#SVC having kernel sigmoid
svm_model4 = SVC(C=3,kernel='sigmoid',degree=5,gamma=6)

In [27]:
svm_model4.fit(x_train,y_train)

SVC(C=3, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=5, gamma=6, kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [28]:
#prediction for sigmoid kernel
pred4=svm_model4.predict(x_test)

In [29]:
#accuracy score
accuracy_score(y_test,pred4)

0.07962962962962963

In [30]:
#confusion matrix
confusion_matrix(y_test,pred4)

array([[ 0,  0,  0,  0, 58,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 52,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 58,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 59,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 43,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 64,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 47,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 59,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 50,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 50,  0,  0,  0,  0,  0]], dtype=int64)

In [31]:
#classification report
print(classification_report(y_test,pred2))

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        58
          1       0.98      0.94      0.96        52
          2       1.00      0.98      0.99        58
          3       1.00      0.97      0.98        59
          4       0.98      0.98      0.98        43
          5       0.95      0.98      0.97        64
          6       0.98      0.98      0.98        47
          7       0.97      0.98      0.97        59
          8       0.94      0.98      0.96        50
          9       0.96      0.98      0.97        50

avg / total       0.98      0.98      0.98       540

