In [8]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
%matplotlib inline
from sklearn.datasets import load_digits

Question 1: Import the dataset from sklearn 

In [37]:
#load_digits
dig=load_digits()
#Question 2: Save X(features) and y(target) as dataframes
x=dig.data
y=dig.target
x.shape, y.shape

((1797, 64), (1797,))

Question 3:Split the dataset into training and testing sets.

In [14]:
#perform split on training data
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size = 0.3, random_state = 2)

Question 4: Use Logistic Regression

In [38]:
#logistic regression
regressor = LogisticRegression()
regressor.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [19]:
#get predicted data
pred = regressor.predict(x_test)

Question 5: Use Logistic Regression

In [16]:
#import libraries
from sklearn.metrics import classification_report
from sklearn import model_selection
from sklearn.metrics import log_loss

In [34]:
#classification metrices
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,pred))

0.9444444444444444


In [22]:
#K fold for cross_validation
kfold = model_selection.KFold(n_splits=10,random_state=5)

In [25]:
result_log_loss=model_selection.cross_val_score(regressor,x,y,cv=kfold,scoring='neg_log_loss')
result_log_loss

array([-0.45798961, -0.14435058, -0.61749705, -0.27323142, -0.27594697,
       -0.12815811, -0.11024468, -0.1233365 , -0.62592303, -0.68553964])

In [26]:
result_r2=model_selection.cross_val_score(regressor,x,y,cv=kfold,scoring='r2')
result_r2

array([0.73184699, 0.86942354, 0.81023661, 0.79423609, 0.82434177,
       0.94343263, 0.92524112, 0.90725247, 0.60169024, 0.82555495])

In [29]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, pred)

0.24074074074074073

In [31]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,pred)

1.3222222222222222

In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[54,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 51,  0,  1,  0,  0,  0,  0,  3,  1],
       [ 0,  0, 54,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 56,  0,  2,  0,  2,  1,  1],
       [ 0,  2,  0,  0, 49,  0,  0,  0,  0,  2],
       [ 0,  0,  0,  0,  0, 56,  0,  1,  0,  2],
       [ 0,  0,  0,  0,  0,  0, 55,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 54,  1,  0],
       [ 0,  5,  0,  1,  0,  0,  0,  0, 41,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0,  3, 40]], dtype=int64)

In [35]:
#classification metrices
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        54
          1       0.88      0.91      0.89        56
          2       1.00      1.00      1.00        54
          3       0.97      0.90      0.93        62
          4       1.00      0.92      0.96        53
          5       0.95      0.95      0.95        59
          6       1.00      0.98      0.99        56
          7       0.95      0.98      0.96        55
          8       0.82      0.87      0.85        47
          9       0.87      0.91      0.89        44

avg / total       0.95      0.94      0.94       540

